INSERT INTO ROL (ID_ROL, NOMBRE_ROL)
VALUES (1, 'Administrador');
INSERT INTO ROL (ID_ROL, NOMBRE_ROL)
VALUES (2, 'Cliente');

INSERT INTO `usuario` (`IDUSUARIO`, `ID_ROL`, `NOMBRE_USUARIO`, `CLAVE`, `USERNAME`) 
VALUES ('11', '1', 'Isabella Solarte', '123', 'isabsolarte'),
 ('12', '1', 'Daniela Riascos', '123', 'driascos');


 INSERT INTO PRODUCTO (IDPRODUCTO, NOMBRE_PRODUCTO, PRECIO, FECHA_FABRICACION)
VALUES (1, 'Camiseta', 20, '2023-01-15');

INSERT INTO PRODUCTO (IDPRODUCTO, NOMBRE_PRODUCTO, PRECIO, FECHA_FABRICACION)
VALUES (2, 'Zapatos deportivos', 50, '2023-02-28');

INSERT INTO PRODUCTO (IDPRODUCTO, NOMBRE_PRODUCTO, PRECIO, FECHA_FABRICACION)
VALUES (3, 'Portátil', 800, '2023-03-10');

INSERT INTO PRODUCTO (IDPRODUCTO, NOMBRE_PRODUCTO, PRECIO, FECHA_FABRICACION)
VALUES (4, 'Cámara digital', 150, '2023-04-05');

INSERT INTO PRODUCTO (IDPRODUCTO, NOMBRE_PRODUCTO, PRECIO, FECHA_FABRICACION)
VALUES (5, 'Reloj inteligente', 100, '2023-05-20');
SELECT P.NOMBRE_PRODUCTO,P.PRECIO 
FROM PRODUCTO P INNER JOIN LISTA_PRODUCTOS LP 
ON P.IDPRODUCTO=LP.IDPRODUCTO INNER JOIN LISTA_COMPRAS LC
ON LP.IDLISTA=LC.IDLISTA INNER JOIN USUARIO US
ON LC.IDUSUARIO=US.IDUSUARIO
WHERE IDUSUARIO=?;